### ISSUE TITLE
TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by msk7131** [jnjaby/AlignFormer#4]
execute command CUDA_VISIBLE_DEVICES=6 python -u basicsr/train.py -opt "options/train/AlignFormer/DAM_train.yml"
occur following error：
Disable distributed.
Traceback (most recent call last):
  File "basicsr/train.py", line 212, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 97, in train_pipeline
    opt['root_path'] = root_path
TypeError: 'tuple' object does not support item assignment

**Comment by jnjaby** [comment]
Hi, this message suggests `opt` is a `tuple` instance here. This could stem from the incompatible version of `basicsr`. Did you run `python setup.py develop` as suggested in the installation?
